// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqivkbdpzdblfikslnbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxaXZrYmRwemRibGZpa3NsbmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMTg3NTQsImV4cCI6MjA3ODc5NDc1NH0.AtbXh_4bYX8Fjqg3A1GZplcBEoNqBgdtlQKg8FseqNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});